<?php
/**
 * ServicePositionInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\ReceiptsV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Receipts API
 *
 * Interface for the partner to get receipts information
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EzzeSiftuz\ReceiptsV2;

/**
 * ServicePositionInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Service information. This field will be present for REFUND and PURCHASE receipt
 * @package     EzzeSiftuz\ReceiptsV2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServicePositionInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ServicePositionInfo"
     */
    public function testServicePositionInfo()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "vat_rate"
     */
    public function testPropertyVatRate()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "service_name"
     */
    public function testPropertyServiceName()
    {
    }

    /**
     * Test attribute "service_type"
     */
    public function testPropertyServiceType()
    {
    }

    /**
     * Test attribute "product_title"
     */
    public function testPropertyProductTitle()
    {
    }

    /**
     * Test attribute "article_number"
     */
    public function testPropertyArticleNumber()
    {
    }

    /**
     * Test attribute "promotion"
     */
    public function testPropertyPromotion()
    {
    }

    /**
     * Test attribute "service_position_items"
     */
    public function testPropertyServicePositionItems()
    {
    }
}
